[package]
name = "perforce-sync"
version = "0.1.0"
authors = ["snake"]

[dependencies]
env_logger = "0.5"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
structopt = "0.2"
time = "0.1"
